apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-api-deployment
spec:
  replicas: 2 # Run 2 copies of our app for availability
  selector:
    matchLabels:
      app: sentiment-api
  template:
    metadata:
      labels:
        app: sentiment-api
    spec:
      containers:
      - name: sentiment-api-container
        image: zaidalam7/sentiment-api:latest # The name of our local Docker image
        imagePullPolicy: Always # Tells K8s to use the local image
        ports:
        - containerPort: 80